language: ruby

rvm:
    - 2.1.10
    - 2.2.4
    - 2.2.6
    - 2.3.3
    - ruby-head

before_script:
    - gem install bundler

script:
    - bundle install
    - bundle exec rake test
    - bundle exec rake doc

